# Generated by Django 6.0.6 on 2026-07-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_customer_order_shipping_address_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_type', models.CharField(choices=[('cat-bundle', 'Cat bundle'), ('dog-bundle', 'Dog bundle')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'bundle enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
