"""
Django settings for petkit_backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def env_str(name, default=""):
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    return value.strip()


def include_www_variants(hosts):
    expanded = []
    for host in hosts:
        if host not in expanded:
            expanded.append(host)
        if host in {"127.0.0.1", "localhost"} or host.startswith("."):
            continue
        variant = host[4:] if host.startswith("www.") else f"www.{host}"
        if variant not in expanded:
            expanded.append(variant)
    return expanded


def postgres_config_from_url(database_url):
    parsed = urlparse(database_url)
    if parsed.scheme not in {"postgres", "postgresql"}:
        raise ValueError("DATABASE_URL must use the postgres:// or postgresql:// scheme.")

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote(parsed.path.lstrip("/")),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or 5432),
        "CONN_MAX_AGE": int(env_str("POSTGRES_CONN_MAX_AGE", "60")),
        "TEST": {
            "NAME": env_str("POSTGRES_TEST_DB", "test_petkit_db"),
        },
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-local-dev-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = include_www_variants(env_list("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost"))
RAILWAY_PUBLIC_DOMAIN = env_str("RAILWAY_PUBLIC_DOMAIN")
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS = include_www_variants([*ALLOWED_HOSTS, RAILWAY_PUBLIC_DOMAIN])

if not DEBUG and SECRET_KEY == "django-insecure-local-dev-key-change-me":
    raise ValueError("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is False.")

if not DEBUG and not ALLOWED_HOSTS:
    raise ValueError("DJANGO_ALLOWED_HOSTS must be set when DJANGO_DEBUG is False.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'allauth',
    'allauth.account',
    'allauth.mfa',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'petkit_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.oauth_providers',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

WSGI_APPLICATION = 'petkit_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = env_str("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {"default": postgres_config_from_url(DATABASE_URL)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env_str("POSTGRES_DB", env_str("PGDATABASE", "petkit_db")),
            "USER": env_str("POSTGRES_USER", env_str("PGUSER", "petkit_admin")),
            "PASSWORD": env_str("POSTGRES_PASSWORD", env_str("PGPASSWORD", "petkit_admin_123!")),
            "HOST": env_str("POSTGRES_HOST", env_str("PGHOST", "127.0.0.1")),
            "PORT": env_str("POSTGRES_PORT", env_str("PGPORT", "5433")),
            "CONN_MAX_AGE": int(env_str("POSTGRES_CONN_MAX_AGE", "60")),
            "TEST": {
                "NAME": env_str("POSTGRES_TEST_DB", "test_petkit_db"),
            },
        }
    }

if not DEBUG:
    default_database = DATABASES["default"]
    missing_database_settings = [
        name
        for name, value in {
            "NAME": default_database.get("NAME"),
            "USER": default_database.get("USER"),
            "HOST": default_database.get("HOST"),
            "PORT": default_database.get("PORT"),
        }.items()
        if not value
    ]
    if missing_database_settings:
        raise ValueError(
            "Production database settings are incomplete. Set DATABASE_URL or the "
            f"POSTGRES_* variables. Missing: {', '.join(missing_database_settings)}."
        )
    if default_database.get("HOST") in {"127.0.0.1", "localhost"}:
        raise ValueError(
            "Production database host cannot be localhost. Set DATABASE_URL or "
            "POSTGRES_HOST to your Railway PostgreSQL service host."
        )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR.parent / 'assets']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Production security and reverse-proxy settings. These remain opt-in for
# local development, while production defaults protect cookies and HTTPS.
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")
csrf_hosts = []
for origin in CSRF_TRUSTED_ORIGINS:
    parsed_origin = urlparse(origin)
    if parsed_origin.scheme and parsed_origin.netloc:
        csrf_hosts.append(parsed_origin.netloc)
if RAILWAY_PUBLIC_DOMAIN:
    csrf_hosts.append(RAILWAY_PUBLIC_DOMAIN)
for host in include_www_variants(csrf_hosts):
    origin = f"https://{host}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
SECURE_HSTS_SECONDS = int(
    os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0")
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS")
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD")

LOGIN_URL = 'customer_account:login'
LOGIN_REDIRECT_URL = 'customer_account:dashboard'
LOGOUT_REDIRECT_URL = 'customer_account:login'

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_LOGOUT_REDIRECT_URL = LOGOUT_REDIRECT_URL
SOCIALACCOUNT_ADAPTER = "shop.adapters.CustomerSocialAccountAdapter"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_STORE_TOKENS = False
MFA_SUPPORTED_TYPES = ["totp", "recovery_codes"]
MFA_TOTP_ISSUER = "Tails Town"
MFA_RECOVERY_CODE_COUNT = 10


def oauth_app(client_id, secret, key="", app_settings=None):
    app = {
        "client_id": client_id,
        "secret": secret,
        "key": key,
    }
    if app_settings:
        app["settings"] = app_settings
    return app


GOOGLE_OAUTH_CLIENT_ID = env_str("GOOGLE_OAUTH_CLIENT_ID")
GOOGLE_OAUTH_CLIENT_SECRET = env_str("GOOGLE_OAUTH_CLIENT_SECRET")
FACEBOOK_OAUTH_CLIENT_ID = env_str("FACEBOOK_OAUTH_CLIENT_ID")
FACEBOOK_OAUTH_CLIENT_SECRET = env_str("FACEBOOK_OAUTH_CLIENT_SECRET")
APPLE_OAUTH_CLIENT_ID = env_str("APPLE_OAUTH_CLIENT_ID")
APPLE_OAUTH_KEY_ID = env_str("APPLE_OAUTH_KEY_ID")
APPLE_OAUTH_TEAM_ID = env_str("APPLE_OAUTH_TEAM_ID")
APPLE_OAUTH_PRIVATE_KEY = env_str("APPLE_OAUTH_PRIVATE_KEY")

BUNDLE_ENQUIRY_SHEET_WEBHOOK_URL = env_str("BUNDLE_ENQUIRY_SHEET_WEBHOOK_URL")

SOCIALACCOUNT_PROVIDERS = {}

if GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET:
    SOCIALACCOUNT_PROVIDERS["google"] = {
        "APPS": [oauth_app(GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET)],
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKCE_ENABLED": True,
        "VERIFIED_EMAIL": True,
        "EMAIL_AUTHENTICATION": True,
    }

if FACEBOOK_OAUTH_CLIENT_ID and FACEBOOK_OAUTH_CLIENT_SECRET:
    SOCIALACCOUNT_PROVIDERS["facebook"] = {
        "APPS": [oauth_app(FACEBOOK_OAUTH_CLIENT_ID, FACEBOOK_OAUTH_CLIENT_SECRET)],
        "METHOD": "oauth2",
        "SCOPE": ["email", "public_profile"],
        "FIELDS": ["id", "email", "name", "first_name", "last_name", "picture"],
        "VERIFIED_EMAIL": env_bool("FACEBOOK_OAUTH_VERIFIED_EMAIL", default=False),
        "EMAIL_AUTHENTICATION": env_bool("FACEBOOK_OAUTH_VERIFIED_EMAIL", default=False),
    }

if APPLE_OAUTH_CLIENT_ID and APPLE_OAUTH_KEY_ID and APPLE_OAUTH_TEAM_ID and APPLE_OAUTH_PRIVATE_KEY:
    SOCIALACCOUNT_PROVIDERS["apple"] = {
        "APPS": [
            oauth_app(
                APPLE_OAUTH_CLIENT_ID,
                APPLE_OAUTH_KEY_ID,
                APPLE_OAUTH_TEAM_ID,
                {"certificate_key": APPLE_OAUTH_PRIVATE_KEY.replace("\\n", "\n")},
            )
        ],
        "VERIFIED_EMAIL": True,
        "EMAIL_AUTHENTICATION": True,
    }

OAUTH_PROVIDER_STATUS = {
    "apple": "apple" in SOCIALACCOUNT_PROVIDERS,
    "facebook": "facebook" in SOCIALACCOUNT_PROVIDERS,
    "google": "google" in SOCIALACCOUNT_PROVIDERS,
}

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "PETKIT <no-reply@petkit.local>")
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", default=False)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", default=False)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
